version: "3.6"

services:

  rabbitmq:
    extends:
      file: ./deploy/docker-compose.yml
      service: rabbitmq
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGER_PORT:-15672}:15672

  web-service:
    extends:
      file: ./deploy/docker-compose.yml
      service: web-service
    ports:
      - ${WEB_SERVICE_PORT:-81}:8080
    depends_on:
      - rabbitmq

  database:
    extends:
      file: ./deploy/docker-compose.yml
      service: database
    ports:
      - ${RABBITMQ_PORT:-5432}:5432

  auth-service:
    extends:
      file: ./deploy/docker-compose.yml
      service: auth-service
    build:
      context: auth-service
    volumes:
      - ./auth-service:/app
    depends_on:
      - rabbitmq
      - database
      - core-service

  core-service:
    extends:
      file: ./deploy/docker-compose.yml
      service: core-service
    build:
      context: core-service
    volumes:
      - ./core-service:/app
    depends_on:
      - rabbitmq
      - database

  adminer:
    extends:
      file: ./deploy/docker-compose.yml
      service: adminer
