version: "3.6"

services:

  rabbitmq:
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGER_PORT:-15672}:15672

  web-service:
    ports:
      - ${WEB_SERVICE_PORT:-81}:8080
    depends_on:
      - rabbitmq

  database:
    ports:
      - ${RABBITMQ_PORT:-5432}:5432

  auth-service:
    build:
      context: auth-service
    volumes:
      - ./auth-service:/app
    depends_on:
      - rabbitmq
      - database
      - core-service

  core-service:
    build:
      context: core-service
    volumes:
      - ./core-service:/app
    depends_on:
      - rabbitmq
      - database

  adminer:
    ports:
      - ${ADMINER_PORT:-63}:8080
