version: "3.6"

services:

  rabbitmq:
    container_name: ${PROJECT_NAME}-rabbitmq
    image: ${RABBITMQ_TAG:-bitnami/rabbitmq:latest}
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      RABBITMQ_PLUGINS: rabbitmq_management,rabbitmq_consistent_hash_exchange
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGER_PORT:-15672}:15672

  web-service:
    container_name: ${PROJECT_NAME}-web-service
    image: egalbox/web-service:2.0.0beta19
    ports:
      - ${WEB_SERVICE_PORT:-80}:8080
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      APP_SERVICE_NAME: web
      RABBITMQ_HOST: ${PROJECT_NAME}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}

      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672
    depends_on:
      - rabbitmq

  auth-database:
    container_name: ${PROJECT_NAME}-auth-database
    image: egalbox/postgres:2.0.0
    restart: always
    ports:
      - ${RABBITMQ_PORT:-5433}:5433
    environment:
      POSTGRES_MULTIPLE_DATABASES: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}

  auth-service:
    container_name: ${PROJECT_NAME}-auth-service
    image: egalbox/auth-service:2.0.0beta20
    environment:
      APP_SERVICE_NAME: auth
      APP_SERVICE_KEY: uZsLnAJz35FWUTVx@eg#Xirv6I*jcw2Y
      DB_HOST: ${PROJECT_NAME}-database
      DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      RABBITMQ_HOST: ${PROJECT_NAME}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672, ${PROJECT_NAME}-database:5432
    depends_on:
      - rabbitmq
      - database

  core-database:
    container_name: ${PROJECT_NAME}-core-database
    image: egalbox/postgres:2.0.0
    restart: always
    ports:
      - ${RABBITMQ_PORT:-5434}:5434
    environment:
      POSTGRES_MULTIPLE_DATABASES: core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}

  core-service:
    container_name: ${PROJECT_NAME}-core-service
    build:
      context: core-service
    environment:
      APP_SERVICE_NAME: core
      APP_SERVICE_KEY: uiA3ZsU#x@ecwgJrv6ITjLV*nzX5FW2Y
      DB_HOST: ${PROJECT_NAME}-database
      DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      RABBITMQ_HOST: ${PROJECT_NAME}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672, ${PROJECT_NAME}-database:5434
    depends_on:
      - rabbitmq
      - database