version: "3.6"

services:

  rabbitmq:
    container_name: ${PROJECT_NAME:-project}-rabbitmq
    image: ${RABBITMQ_TAG:-bitnami/rabbitmq:latest}
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      RABBITMQ_PLUGINS: rabbitmq_management,rabbitmq_consistent_hash_exchange


  web-service:
    container_name: ${PROJECT_NAME:-project}-web-service
    image: egalbox/web-service:2.2.1
    restart: on-failure
    environment:
      PROJECT_NAME: ${PROJECT_NAME:-project}
      APP_SERVICE_NAME: web
      RABBITMQ_HOST: ${PROJECT_NAME:-project}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672
    depends_on:
      - rabbitmq

  database:
    container_name: ${PROJECT_NAME:-project}-database
    image: egalbox/postgres:2.0.0
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: auth, core
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}

  auth-service:
    container_name: ${PROJECT_NAME:-project}-auth-service
    tty: true
    restart: on-failure
    environment:
      APP_SERVICE_NAME: auth
      APP_SERVICE_KEY: zF0aM@I5*D2UTBurR6ijspGQ^f#VXxky
      APP_SERVICES: core:Z28jL*3l6c^qJ7VsnxNaYBg%Pei1MEFI
      DB_HOST: ${PROJECT_NAME:-project}-database
      DB_DATABASE: auth
      DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      RABBITMQ_HOST: ${PROJECT_NAME:-project}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME:-project}-rabbitmq:5672, ${PROJECT_NAME:-project}-database:5432
    depends_on:
      - rabbitmq
      - database
      - core-service

  core-service:
    container_name: ${PROJECT_NAME:-project}-core-service
    tty: true
    restart: on-failure
    environment:
      APP_SERVICE_NAME: core
      APP_SERVICE_KEY: Z28jL*3l6c^qJ7VsnxNaYBg%Pei1MEFI
      DB_HOST: ${PROJECT_NAME:-project}-database
      DB_USERNAME: postgres
      DB_DATABASE: core
      DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      RABBITMQ_HOST: ${PROJECT_NAME:-project}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME:-project}-rabbitmq:5672, ${PROJECT_NAME:-project}-database:5432
    depends_on:
      - rabbitmq
      - database


  adminer:
    image: adminer
    restart: always
    ports:
      - 63:8080
